site_name:        ICDataServer.jl
repo_url:         https://github.com/PainterQubits/ICDataServer.jl
site_description: Automatic logging of measurement data and metadata.
site_author:      Andrew Keller

theme: material
extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Design: design.md
- API:
    - 'Jobs': jobs.md
    - 'Users': users.md
    - 'Servers': servers.md
    - 'Instruments': instruments.md
- Miscellaneous:
    - 'License': LICENSE.md
